home_path = './tests/example';

title_notes = ["68W5X99W59"];

virtual_entities = {
  'VJP2M3RCRH': {psplx: '# <++>\n^personal', html: '<div id="VJP2M3RCRH">\n  <h1 id="user-content-">&lt;++&gt;</h1>\n  <div class="type-list">\n    <div class="type">personal</div>\n  </div>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=MJRX49RR78" onclick="return open_note(\'MJRX49RR78\');">Redacting</a></p>\n  </div>\n</div>\n', tsplx: '_ a personal ;\n  backlink MJRX49RR78 ;\n  t:virtual_id "VJP2M3RCRH" ;\n', title: '<++>'},
  'VQW85F744F': {psplx: '# Non-public Virtual\n^personal', html: '<div id="VQW85F744F">\n  <h1 id="user-content-non-public-virtual">Non-public Virtual</h1>\n  <div class="type-list">\n    <div class="type">personal</div>\n  </div>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=MJRX49RR78" onclick="return open_note(\'MJRX49RR78\');">Redacting</a></p>\n    <p><a class="note-link" href="?n=5P3QHFGX2Q" onclick="return open_note(\'5P3QHFGX2Q\');">Virtual List</a></p>\n  </div>\n</div>\n', tsplx: '_ a personal ;\n  backlink MJRX49RR78 ;\n    5P3QHFGX2Q ;\n  name "Non-public Virtual" ;\n  t:virtual_id "VQW85F744F" ;\n', title: 'Non-public Virtual'},
  'VCMHGGJ222': {psplx: '# Thin -> Arrow\n^note', html: '<div id="VCMHGGJ222">\n  <h1 id="user-content-thin---arrow">Thin -&gt; Arrow</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Thin -> Arrow" ;\n  t:virtual_id "VCMHGGJ222" ;\n', title: 'Thin -> Arrow'},
  '34HF3RV3VR': {psplx: '# "Page Syntax"\n^note', html: '<div id="34HF3RV3VR">\n  <h1 id="user-content-page-syntax">"Page Syntax"</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "\"Page Syntax\"" ;\n  t:virtual_id "34HF3RV3VR" ;\n', title: '"Page Syntax"'},
  '69739RJ7MF': {psplx: '# "Page Syntax" > "Test 1 (H2) "\n^note', html: '<div id="69739RJ7MF">\n  <h1 id="user-content-page-syntax--test-1-h2-">"Page Syntax" &gt; "Test 1 (H2) "</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "\"Page Syntax\" > \"Test 1 (H2) \"" ;\n  t:virtual_id "69739RJ7MF" ;\n', title: '"Page Syntax" > "Test 1 (H2) "'},
  'WM4FXFJHRW': {psplx: '# " Page Syntax " > " Test 1 (H2) "\n^note', html: '<div id="WM4FXFJHRW">\n  <h1 id="user-content--page-syntax----test-1-h2-">" Page Syntax " &gt; " Test 1 (H2) "</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "\" Page Syntax \" > \" Test 1 (H2) \"" ;\n  t:virtual_id "WM4FXFJHRW" ;\n', title: '" Page Syntax " > " Test 1 (H2) "'},
  'WXF7QMH956': {psplx: '# Quoted Page Title\n^note', html: '<div id="WXF7QMH956">\n  <h1 id="user-content-quoted-page-title">Quoted Page Title</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Quoted Page Title" ;\n  t:virtual_id "WXF7QMH956" ;\n', title: 'Quoted Page Title'},
  'V89VMV4HMP': {psplx: '# Title with quoted "end"\n^note', html: '<div id="V89VMV4HMP">\n  <h1 id="user-content-title-with-quoted-end">Title with quoted "end"</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Title with quoted \"end\"" ;\n  t:virtual_id "V89VMV4HMP" ;\n', title: 'Title with quoted "end"'},
  'W6672VQWWQ': {psplx: '# "Title" with quoted start\n^note', html: '<div id="W6672VQWWQ">\n  <h1 id="user-content-title-with-quoted-start">"Title" with quoted start</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "\"Title\" with quoted start" ;\n  t:virtual_id "W6672VQWWQ" ;\n', title: '"Title" with quoted start'},
  'J2H9VH8QRF': {psplx: '# Title "with quoted" middle\n^note', html: '<div id="J2H9VH8QRF">\n  <h1 id="user-content-title-with-quoted-middle">Title "with quoted" middle</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Title \"with quoted\" middle" ;\n  t:virtual_id "J2H9VH8QRF" ;\n', title: 'Title "with quoted" middle'},
  '3JWVG2XP3X': {psplx: '# Title with -> arrows -> Page Syntax\n^note', html: '<div id="3JWVG2XP3X">\n  <h1 id="user-content-title-with---arrows---page-syntax">Title with -&gt; arrows -&gt; Page Syntax</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Title with -> arrows -> Page Syntax" ;\n  t:virtual_id "3JWVG2XP3X" ;\n', title: 'Title with -> arrows -> Page Syntax'},
  'J7FR9RRC9Q': {psplx: '# Title with > greater than > Page Syntax\n^note', html: '<div id="J7FR9RRC9Q">\n  <h1 id="user-content-title-with--greater-than--page-syntax">Title with &gt; greater than &gt; Page Syntax</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Title with > greater than > Page Syntax" ;\n  t:virtual_id "J7FR9RRC9Q" ;\n', title: 'Title with > greater than > Page Syntax'},
  'H5HW26F642': {psplx: '# > Title with > greater than > Page Syntax\n^note', html: '<div id="H5HW26F642">\n  <h1 id="user-content--title-with--greater-than--page-syntax">&gt; Title with &gt; greater than &gt; Page Syntax</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "> Title with > greater than > Page Syntax" ;\n  t:virtual_id "H5HW26F642" ;\n', title: '> Title with > greater than > Page Syntax'},
  'JMV9HHMRGF': {psplx: '# Page Syntax->\n^note', html: '<div id="JMV9HHMRGF">\n  <h1 id="user-content-page-syntax-">Page Syntax-&gt;</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Page Syntax->" ;\n  t:virtual_id "JMV9HHMRGF" ;\n', title: 'Page Syntax->'},
  'V5Q869RHM9': {psplx: '# Page Syntax ->\n^note', html: '<div id="V5Q869RHM9">\n  <h1 id="user-content-page-syntax--">Page Syntax -&gt;</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Page Syntax ->" ;\n  t:virtual_id "V5Q869RHM9" ;\n', title: 'Page Syntax ->'},
  'WH4FQQP965': {psplx: '# Title With > Greater Than ->\n^note', html: '<div id="WH4FQQP965">\n  <h1 id="user-content-title-with--greater-than--">Title With &gt; Greater Than -&gt;</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Title With > Greater Than ->" ;\n  t:virtual_id "WH4FQQP965" ;\n', title: 'Title With > Greater Than ->'},
  'W7G6HGX53X': {psplx: '# Title with spaces\n^note', html: '<div id="W7G6HGX53X">\n  <h1 id="user-content-title-with-spaces">Title with spaces</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "Title with spaces" ;\n  t:virtual_id "W7G6HGX53X" ;\n', title: 'Title with spaces'},
  'W645HXMQXM': {psplx: '# ->\n^note', html: '<div id="W645HXMQXM">\n  <h1 id="user-content--">-&gt;</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name "->" ;\n  t:virtual_id "W645HXMQXM" ;\n', title: '->'},
  'WJ67FXMP58': {psplx: '# >\n^note', html: '<div id="WJ67FXMP58">\n  <h1 id="user-content-">&gt;</h1>\n  <h4>Backlinks</h4>\n  <div class="backlinks">\n    <p><a class="note-link" href="?n=XHWXV3888W" onclick="return open_note(\'XHWXV3888W\');">Page Links</a></p>\n  </div>\n</div>\n', tsplx: '_ a note ;\n  backlink XHWXV3888W ;\n  name ">" ;\n  t:virtual_id "WJ67FXMP58" ;\n', title: '>'},
};
